### ISSUE TITLE
No text when playing US game Just Dance 4 on a Japanese Wii

### ISSUE THREAD

**Issue by rjsh** [iGlitch/MinimaLauncher#4]
I was able to launch and play the US version of Just Dance 4 using MinimaLauncher in the Homebrew Channel v1.1.2. Homebrew was installed using Letterbomb.

MinimaLauncher was downloaded from here: https://www.mediafire.com/file/f7bgzfinnbj6yyk/MinimaLauncher.zip

System menu version 4.3J

However, there is no text on menus inside the game. Please see the screenshot below:
![image](https://user-images.githubusercontent.com/6629709/50357295-58415800-050a-11e9-841e-b695bb7cd038.png)

**Comment by iGlitch** [comment]
Hi, sorry I am half a year late XD
This is an interesting find, seems that the langpatch wasn't applied for some reason.
I can't test this setup myself, but if you are still interested, can you try [this version](https://www.dropbox.com/s/w2rz2j2hix0anux/boot.dol?dl=1)?
